config/routes.rb
Rails.application.routes.draw do
  resources :dashboard, only: :index
  namespace :dashboard do
    resources :items, except: :show
    resources :users, only: :index 
    resources :orders, only: :index
  end

  devise_for :users
  root to: 'items#index'
  resources :users, only: :show do
    collection do
      get 'cart', to: 'shopping_carts#index'
      post 'cart/create', to: 'shopping_carts#create'
      delete 'cart', to: 'shopping_carts#destroy'
      get 'cart_history_index'
      get 'cart_history_show/:num', to: "users#cart_history_show", as: "cart_history"
    end
  end
  
  resources :items, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :shopping_cart_items
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  acts_as_shopping_cart
  scope :set_user_cart, -> (user) { user_cart = where(user_id: user.id, buy_flag: false)&.last
    user_cart.nil? ? ShoppingCart.create(user_id: user.id)
                   : user_cart }
  scope :bought_carts, -> { where(buy_flag: true) }
  scope :search_carts_by_user, -> (user) { where(user_id: user) }
  scope :search_bought_carts_by_user, -> (user) { bought_carts.search_carts_by_user(user) }                  


  def tax_pct
    0
  end
  belongs_to :user
end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ApplicationRecord
  acts_as_shopping_cart_item
  scope :user_cart_items, -> (user_shoppingcart) { where(owner_id: user_shoppingcart) }

  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         with_options presence: true do
          validates :company_name
          validates :phone_number, format: { with: /\A\d{10,11}\z/, message: 'は半角数字で入力してください' }
         end

         validates :password, :password_confirmation,
            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は、半角英数字で入力してください' }
         has_many :shopping_carts
         has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth
  
  def after_sign_in_path_for(resource)
    if  current_user.try(:admin?)
      dashboard_index_path
    else
        root_path
    end
  end

    def after_sign_out_path_for(resource)
        new_user_session_path
    end
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:company_name, :phone_number])
  end
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end
end

app/controllers/dashboard/items_controller.rb
class Dashboard::ItemsController < ApplicationController
  before_action :authenticate_user!
  layout "dashboard/dashboard"
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to dashboard_items_path
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :image)
  end
end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < ApplicationController
  before_action :authenticate_user!
  layout  "dashboard/dashboard"

  def index
    @orders = ShoppingCart.bought_carts
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  before_action :authenticate_user!
  layout  "dashboard/dashboard"

  def index
    @users = User.where(admin: 0)
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard/dashboard'
  def index
    
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end
  
  def show
    @item = Item.find(params[:id])
 end

end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :set_cart, only: [:index, :create, :destroy]

  def index
    @user_cart_items = ShoppingCartItem.user_cart_items(@user_cart)
  end

  def show
    @cart = ShoppingCart.find(user_id: current_user)
  end

  def create
    @item = Item.find(item_params[:item_id])
    @user_cart.add(@item, item_params[:price].to_i, item_params[:quantity].to_i)
    redirect_to cart_users_path
  end
 

  def destroy
    @user_cart.buy_flag = true
    @user_cart.save
  end
  
  private
    def set_cart
      @user_cart = ShoppingCart.set_user_cart(current_user)
    end

    def item_params
      params.permit(:item_id, :price, :quantity)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
  end

  def cart_history_index
    @orders = ShoppingCart.search_bought_carts_by_user(current_user)
  end

  def cart_history_show
   
    @cart = ShoppingCart.find(params[:num])
    @cart_items = ShoppingCartItem.user_cart_items(@cart.id)
  end

 
  

  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/dashboard/items_helper.rb
module Dashboard::ItemsHelper
end

app/helpers/dashboard/orders_helper.rb
module Dashboard::OrdersHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/items/index.html.erb
<div class="w-75 mt-2">   
  <h1>商品管理</h1>
  <table class="table table-responsive mt-5">

    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">画像</th>
        <th scope="col">商品名</th>
        <th scope="col">価格</th>
        
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
      <tr>
        <th scope="row"><%= item.id %></td>
        <div class="image">
         <td><%= image_tag item.image, class: "img-fluid h-10" %></td>
        </div>
        <td><%= item.name %></td>
        <td>¥<%= item.price %></td>
        
      </tr>
      <% end %>
    </tbody>
  </table>
</div> 

app/views/dashboard/items/new.html.erb
<div class="w-75 mt-2">   
  <div class="w-51">
    <h1>商品登録</h1>

    <hr>

    <%= form_with model: @item, url: dashboard_items_path, id: 'new_post', local: true do |f| %>
      <div class="form-inline mt-4 mb-4 row">
         
          
           <%= f.file_field :image%>
         
      </div>

      <div class="form-inline mt-4 mb-4 row">
        <%= f.label "商品名", class: "col-2 d-flex justify-content-start" %>
        <%= f.text_field :name, class: "form-control col-8 btn-outline-dark" %>
      </div>


      <div class="form-inline mt-4 mb-4 row">
        <%= f.label "価格", class: "col-2 d-flex justify-content-start" %>
        <%= f.text_field :price, class: "form-control col-8 btn-outline-dark" %>
      </div>

    

      <%= f.submit "商品を登録", class:"btn item-submit-button btn-success" %>
    <% end %>

    <div class="mt-4"><%= link_to "商品一覧に戻る", dashboard_items_path, class: "btn btn-outline-secondary" %></div>
  </div>
</div>

app/views/dashboard/orders/index.html.erb
<div class="w-75 mt-2">   
  <h1>レンタル受注一覧</h1>
  
    <table class="table table-responsive mt-5">

          <thead>
            <tr>
              <th scope="col">注文番号</th>
              <th scope="col">購入日時</th>
              <th scope="col">合計金額</th>
              <th scope="col">テナントid</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
            <tr>
              <td><%= order.id %></td>
              <td><%= order.updated_at.to_datetime.strftime("%Y-%m-%d %H:%M:%S") %></td>
              <td><%= order.total.fractional / 100 %></td>
              <td><%= order.user_id %></td>
            </tr>
            <% end %>
          </tbody>
    </table>
  
</div>

app/views/dashboard/users/index.html.erb
<div class="w-75 mt-2">   
  <h1>テナント一覧</h1>
  <table class="table table-responsive mt-5">

    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">テナント名</th>
        <th scope="col">電話番号</th>
        <th scope="col">Email</th>
        
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= user.id %></td>
        <td><%= user.company_name %></td>
        <td><%= user.phone_number %></td> 
        <td><%= user.email %></td>
        
        
      </tr>
      <% end %>
    </tbody>
  </table>
</div> 

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class='item-contents'>
    <div class="subtitle" >
      レンタル商品一覧
    </div>
    <ul class='item-lists'>
     <% @items.each do |item| %>
      <li class='list'>
        <%= link_to item_path(item.id) do %>
          <div class='item-img-content'>
            <%= image_tag item.image, class: "item-img" %>
            <% end %>
          </div>
          <div class='item-info'>
            <h3 class='item-name'>
              <%= item.name %>
            </h3>
            <div class='item-price'>
              <span><%= item.price %>円</span>
            </div>
          </div>
      </li>
     <% end %> 
    </ul> 
  </div>
</div>     
<%= render "shared/footer"%>

app/views/items/show.html.erb
<%= render "shared/header" %>

  <div class="d-flex justify-content-center mt-4 mb-4">
    <div class="row w-75">
      <div class="col-5 offset-1 ">
        <%= image_tag @item.image, class: "w-100 img-fuild" %>
      </div>

      <div class="col ">
        <div class="d-flex flex-column">
          <h1 class="">
           <%= @item.name %>
          </h1>
        
          <hr>
          <p class="d-flex align-items-end">
            ￥<%= @item.price %>（税込）
          </p>
          <hr>
        </div>

        <% if user_signed_in? %>
          <%= form_with url: cart_create_users_path, local: true do |f| %>
            <%= f.hidden_field :item_id, value: @item.id %>
            <%= f.hidden_field :name, value: @item.name %>
            <%= f.hidden_field :price, value: @item.price %>
            <div class="form-group row">
              <%= f.label "数量", class: "col-sm-2 col-form-label" %>
              <div class="col-sm-10">
                <%= f.number_field :quantity, min:1, value:1, class: "form-control  w-25 "%>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col-7">
                <%= f.submit "カートに入れる", class: "btn ics-favorite-add-cart btn-success text-black w-100" %>
              </div>
            </div>  
          <% end %>
        <% end %> 
      </div>  
    </div>
  </div> 

<%= render "shared/footer"%>      

app/views/layouts/dashboard/_sidebar.html.erb
<div class="container ml-3">
  <h2>受注管理</h2>
  <div class="d-flex flex-column mb-2">
    <label class="ims-sidebar-category-label mt-1">
      <%= link_to "受注一覧", dashboard_orders_path, class: 'links' %>
    </label>
  </div>

  <h2>商品管理</h2>
  <div class="d-flex flex-column mt-2 mb-2">
    <label class="ims-sidebar-category-label mt-1">
      <%= link_to "商品一覧", dashboard_items_path, class: 'links' %>
    </label>
    <label class="ims-sidebar-category-label mt-1">
      <%= link_to "商品登録", new_dashboard_item_path, class: 'links' %>
    </label>
  </div>

  <h2>テナント管理</h2>
  <div class="d-flex flex-column">
    <label class="ims-sidebar-category-label mt-1">
      <%= link_to "テナント一覧", dashboard_users_path, class: 'links' %>
    </label>
  </div>

</div>

app/views/layouts/dashboard/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IMS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/8484570c7b.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

  </head>

  <body>
  <%= render "shared/header" %>
    <div class="row">  
        <div class="col-3 mt-3">
          <%= render partial: 'layouts/dashboard/sidebar' %>
        </div>
         <div class="col">
          <main class="py-4 mb-5">
            <%= yield %>
          </main>
        </div>
    </div>
  </body>
</html>

app/views/shopping_carts/destroy.html.erb
<%= render "shared/second-header"%>
<div class="contents">
  <div class="content">
    <h3>レンタルを承りました。<br>
    ありがとうございます。</h3>
    
    <%= link_to 'トップページへ戻る',root_path, class: 'btn' %>
  </div>
</div>

<%= render "shared/footer"%> 

app/views/shopping_carts/index.html.erb
<%= render "shared/header" %>
<div class="container d-flex justify-content-center mt-3">
  <div class="w-75">
    <h1>ショッピングカート</h1>

    <div class="offset-8 col-4">
      <div class="row">
        <div class="col-6">
          <h2>数量</h2>
        </div>
        <div class="col-6">
          <h2>小計</h2>
        </div>
      </div>
    </div>

    <hr>

    <div class="row">
      <% @user_cart_items.each do |user_cart_item| %>
        <% item = Item.find(user_cart_item.item_id) %>
        <div class="col-md-2 mt-2">
          <%= link_to item_path(item) do %>
              <%= image_tag item.image, class: "img-fuild w-100" %>
          <% end %>
        </div>
        <div class="col-md-6 mt-4">
          <h3 class="mt-4"><%= item.name %></h3>
        </div>
        <div class="col-md-2">
          <h3 class="w-100 mt-4"><%= user_cart_item.quantity %></h3>
        </div>
        <div class="col-md-2">
          <h3 class="w-100 mt-4">￥<%= user_cart_item.price_cents * user_cart_item.quantity %></h3>
        </div>
      <% end %>
    </div>

    <hr>

    <div class="offset-8 col-4">
      <div class="row">
        <div class="col-6">
          <h2>合計</h2>
        </div>
        <div class="col-6">
          <h2>￥<%= @user_cart.total.fractional / 100 %></h2>
        </div>
        
      </div>
    </div>
    <div class= "d-flex justify-content-end mt-3">
      <%= link_to "レンタルを続ける", items_path, class: "btn ics-favorite-button border-dark text-dark mr-3" %>
      <% if @user_cart_items.present?%>
       <%= link_to "レンタルを確定する", cart_users_path, method: :delete,class: "btn ics-submit-button btn-warning text-dark" %>
      <%end%>
    </div>
  </div>
</div>

<%= render "shared/footer"%>

app/views/users/cart_history_index.html.erb
<%= render "shared/header" %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <span>
        <%= link_to "マイページ", user_path(current_user.id) %> > 注文履歴
      </span>

      <div class="container mt-4">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">注文番号</th>
              <th scope="col">購入日時</th>
              <th scope="col">合計金額</th>
              <th scope="col">詳細</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
            <tr>
              <td><%= order.id %></td>
              <td><%= order.updated_at.to_datetime.strftime("%Y-%m-%d %H:%M:%S") %></td>
              <td><%= order.total.fractional / 100 %></td>
              <td>
                <%= link_to "#{ order.id }",cart_history_users_path(order) %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      
    </div>
  </div>
</div>
<%= render "shared/footer"%>

app/views/users/cart_history_show.html.erb
<%= render "shared/header" %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <span>
        <%= link_to "マイページ", user_path(current_user.id) %> > <%= link_to "注文履歴", cart_history_index_users_path %> > 注文履歴詳細
      </span>

      <h1 class="mt-3">注文履歴詳細</h1>

      <h4 class="mt-3">ご注文情報</h4>

      <hr>

      <div class="row">
        <div class="col-5 mt-2">
          注文番号
        </div>
        <div class="col-7 mt-2">
          <%= @cart.id %>
        </div>

        <div class="col-5 mt-2">
          注文日時
        </div>
        <div class="col-7 mt-2">
          <%= @cart.updated_at.strftime("%Y-%m-%d %H:%M:%S") %>
        </div>
        

        <div class="col-5 mt-2">
          合計金額
        </div>
        <div class="col-7 mt-2">
          ￥<%= @cart.total.fractional / 100 %>
        </div>

        <div class="col-5 mt-2">
          点数
        </div>
        <div class="col-7 mt-2">
          <%= ShoppingCartItem.user_cart_items(@cart.id).count %>点
        </div>

      </div>

      <hr>

      <div class="row">
        <% @cart_items.each do |cart_item| %>
          <% item = Item.find(cart_item.item_id) %>
          <div class="col-md-5 mt-2">
            <%= link_to item_path(item), class: "ml-4" do %>
                <%= image_tag item.image, class: "img-fuild w-75" %>
            <% end %>
          </div>
          <div class="col-md-7 mt-2">
            <div class="flex-cloumn">
              <p class="mt-4"><%= item.name %></p>
              <div class="row">
                <div class="col-2 mt-2">
                  数量
                </div>
                <div class="col-10 mt-2">
                  <%= cart_item.quantity %>
                </div>
  
                <div class="col-2 mt-2">
                  小計
                </div>
                <div class="col-10 mt-2">
                  ￥<%= price = cart_item.price_cents * cart_item.quantity %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer"%>

app/views/users/mypage.html.erb
<%= render "shared/header" %>

<div class="mein-container">
  <div class="w-50">
    
    <h1>マイページ</h1>

    <hr>

    <div class="container">
      <div class="d-flex justify-content-between">
        <div class="row">
          <div class="col-2 d-flex align-items-center">
            <i class="fas fa-archive fa-3x"></i>
          </div>
          <div class="col-9 d-flex align-items-center ml-2 mt-3">
            <div class="d-flex flex-column">
              <label for="user-name">レンタル履歴</label>
              <p>レンタル履歴を確認できます</p>
            </div>
          </div>
        </div>
        <div class="d-flex align-items-center">
          <%= link_to users_mypage_path do %>
            <i class="fas fa-chevron-right fa-2x"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer"%>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="mein-container">
  <div class="w-50">
    
    <h1>マイページ</h1>

    <hr>

    <div class="container">
      <div class="d-flex justify-content-between">
        <div class="row">
          <div class="col-2 d-flex align-items-center">
            <i class="fas fa-archive fa-3x"></i>
          </div>
          <div class="col-10 d-flex align-items-center ml-2 mt-3">
            <div class="d-flex flex-column">
              <label for="user-name">レンタル履歴</label>
              <p>レンタル履歴を確認できます</p>
            </div>
          </div>
        </div>
        <div class="d-flex align-items-center">
          <%= link_to cart_history_index_users_path do %>
            <i class="fas fa-chevron-right fa-2x"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer"%>